name: testy
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 3 minutes
        run: sleep 180s 
        shell: bash 

      - name: Deliberately fail the job
        run: |
          echo "Failing the workflow "
          exit 1
